### ISSUE TITLE
Is trulioo-react works with antd Form?

### ISSUE THREAD

**Issue by thang40** [Trulioo/trulioo-react#53]
I'm about to integrate trulioo into my project with ant design, i wonder if trulioo-react works along with ant design form?🔢

**Comment by mkotsollaris** [comment]
AFAIK, ant design could be applied through CSS, so if you were to load the CSS `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.23.6/antd.min.css">`, the expectation would be that the form would load with ant styling. 

This is how the default style looks from a quick test I ran locally:

![image](https://user-images.githubusercontent.com/8595514/68608722-6c66ae80-0468-11ea-8e23-6152df7aa269.png)

To modify any component within the form, please have a look at our [styling guide](https://github.com/Trulioo/trulioo-react/blob/master/STYLING.md). Should you have more questions, do not hesitate to ask!

**Comment by mkotsollaris** [comment]
Closing this issue.
