### ISSUE TITLE
Object.fromEntries is not a function

### ISSUE THREAD

**Issue by ekkis** [Trulioo/trulioo-react#75]
swinging blindly at figuring out what I need to do, I've got this:
```js
import styled from "styled-components";
import { EmbedID } from "trulioo-react";

const additionalFields = {
    title: 'Additional Fields',
    type: 'object',
    required: ['name', 'age'],
    properties: {
      name: {
        title: 'What is your name?',
        type: 'string',
      },
      age: {
        title: 'What is your age?',
        type: 'number',
      },
      color: {
        title: 'What is your favourite color?',
        type: 'string',
        enum: ['red', 'yellow', 'blue'],
      },
    },
  };

const handleResponse = (e) => {
    console.dir(e, {depth: null});
}

const handleSubmit = (e) => {
    console.dir(e, {depth: null});
}

function Profile({ user }) {
  return (
    <div>
        <h2>Compliance</h2>
        <EmbedID url='http://localhost:3000/' 
            handleResponse={handleResponse} 
            handleSubmit={handleSubmit}
            additionalFields={additionalFields} 
            />
    </div>
  );
}

export default Profile;
```

and the error I get:

> TypeError: Object.fromEntries is not a function
>     at convertToNameTypeObjectArray (/Users/ekkis/dev/node_modules/trulioo-react/dist/actions/constantNationalIds.js:44:17)
>     at combineTypesToSingleObject (/Users/ekkis/dev/node_modules/trulioo-react/dist/actions/constantNationalIds.js:90:26)
>     at Object.<anonymous> (/Users/ekkis/dev/node_modules/trulioo-react/dist/actions/constantNationalIds.js:97:18)
>     at Module._compile (internal/modules/cjs/loader.js:721:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:657:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/Users/ekkis/dev/node_modules/trulioo-react/dist/actions/index.js:32:51)
>     at Module._compile (internal/modules/cjs/loader.js:721:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)

help?

**Comment by mkotsollaris** [comment]
Please use the newest guidelines of EmbedID, which can be [found here](https://gateway-admin.trulioo.com/).
