### ISSUE TITLE
How to access configuration?

### ISSUE THREAD

**Issue by ekkis** [Trulioo/trulioo-react#76]
at this link:

https://gateway-admin.trulioo.com/documentation/embedid

we find the statement: "Accesses your Trulioo configuration to see what countries you have and what fields are available for each country."

but the documentation gives the reader no idea how to set the configuration.  I've looked all over the site for a place where countries can get configured but find nothing

can we please edit the docs to handhold us newbies? because at present it isn't sufficient to make us productive

the Trulioo home page indicates "Get up and running in minutes"... for me that's going to be close to 100 minutes

**Comment by mkotsollaris** [comment]
Our documentation and integration guidelines have been upgraded. Please see this [https://gateway-admin.trulioo.com/manager](https://gateway-admin.trulioo.com/manager)
